general: &general
  port:                 <%= ENV["PORT"] %>
  localhost:            <%= ENV["LOCALHOST"] %>

postgresql: &postgresql
  postgresql_db:        <%= ENV["POSTGRESQL_DB"] %>
  postgresql_host:      <%= ENV["POSTGRESQL_HOST"] %>
  postgresql_port:      <%= ENV["POSTGRESQL_PORT"] %>
  postgresql_user:      <%= ENV["POSTGRESQL_USER"] %>
  postgresql_password:  <%= ENV["POSTGRESQL_PASSWORD"] %>

development:
  <<: *general
  <<: *postgresql
  secret_key_base:      <%= ENV["SECRET_KEY_BASE"] %>

test:
  <<: *general
  <<: *postgresql
  secret_key_base:      <%= ENV["SECRET_KEY_BASE"] %>


production:
  <<: *general
  <<: *postgresql
  secret_key_base:      <%= ENV["SECRET_KEY_BASE"] %>
